# EXCLUDE_TERMS = [
#     "sports",
#     "football",
#     "cricket",
#     "basketball",
#     "baseball",
#     "soccer",
#     "olympic",
#     "tennis",
#     "match",
#     "score",
#     "game",
#     "player",
#     "coach",
#     "movie",
#     "film",
#     "cinema",
#     "music",
#     "concert",
#     "festival",
#     "celebrity",
#     "actor",
#     "actress",
#     "star",
#     "singer",
#     "awards",
#     "fashion",
#     "gossip",
#     "TikTok",
#     "YouTube",
#     "Instagram",
#     "stock",
#     "IPO",
#     "startup",
#     "crypto",
#     "NFT",
#     "token",
#     "app launch",
#     "app update",
#     "product launch",
#     "product review",
#     "sale",
#     "discount",
#     "shopping",
#     "real estate",
#     "lottery",
#     "gambling",
#     "casino",
#     "advertising",
#     "promotion",
#     "PR",
#     "gaming",
#     "eSports",
#     "anime",
#     "manga",
# ]

EXCLUDE_TERMS = {
    'en': [
        "sports",
        "football",
        "cricket",
        "basketball",
        "baseball",
        "soccer",
        "olympic",
        "tennis",
        "match",
        "score",
        "game",
        "player",
        "coach",
        "movie",
        "film",
        "cinema",
        "music",
        "concert",
        "festival",
        "celebrity",
        "actor",
        "actress",
        "star",
        "singer",
        "awards",
        "fashion",
        "gossip",
        "TikTok",
        "YouTube",
        "Instagram",
        "stock",
        "IPO",
        "startup",
        "crypto",
        "NFT",
        "token",
        "app launch",
        "app update",
        "product launch",
        "product review",
        "sale",
        "discount",
        "shopping",
        "real estate",
        "lottery",
        "gambling",
        "casino",
        "advertising",
        "promotion",
        "PR",
        "gaming",
        "eSports",
        "anime",
        "manga",
    ],
    'ja': [
        "スポーツ", 
        "サッカー", 
        "映画", 
        "音楽", 
        "有名人", 
        "株式", 
        "IPO", 
        "スタートアップ", 
        "受賞", 
        "フェスティバル",
        "コンサート", 
        "ゲーム", 
        "暗号通貨", 
        "NFT", 
        "TikTok", 
        "YouTube", 
        "インスタグラム", 
        "セール", 
        "割引", 
        "ファッション", 
        "カジノ"
    ],
    'zh-CN': [
        "体育", 
        "足球", 
        "电影", 
        "音乐", 
        "名人", 
        "股票", 
        "IPO", 
        "创业", 
        "奖项", 
        "节日",
        "音乐会", 
        "游戏", 
        "加密货币", 
        "NFT", 
        "抖音", 
        "YouTube", 
        "Instagram", 
        "促销", 
        "折扣", 
        "时尚", 
        "赌场"
    ],
    'zh-TW': [
        "體育", 
        "足球", 
        "電影", 
        "音樂", 
        "名人", 
        "股票", 
        "IPO", 
        "創業", 
        "獎項", 
        "節慶",
        "音樂會", 
        "遊戲", 
        "加密貨幣", 
        "NFT", 
        "抖音", 
        "YouTube", 
        "Instagram", 
        "促銷", 
        "折扣", 
        "時尚", 
        "賭場"
    ],
    'es': [
        "deportes", 
        "fútbol", 
        "película", 
        "música", 
        "celebridad", 
        "acciones", 
        "IPO", 
        "startup", 
        "premio", 
        "festival",
        "concierto", 
        "juego", 
        "cripto", 
        "NFT", 
        "TikTok", 
        "YouTube", 
        "Instagram", 
        "venta", 
        "descuento", 
        "moda", 
        "casino"
    ],
    'de': [
        "sport", 
        "fußball", 
        "film", 
        "musik", 
        "promi", 
        "aktie", 
        "IPO", 
        "startup", 
        "preis", 
        "festival",
        "konzert", 
        "spiel", 
        "krypto", 
        "NFT", 
        "TikTok", 
        "YouTube", 
        "Instagram", 
        "verkauf", 
        "rabatt", 
        "mode", 
        "casino"
    ],
    'ru': [
        "спорт", 
        "футбол", 
        "фильм", 
        "музыка", 
        "знаменитость", 
        "акции", 
        "IPO", 
        "стартап", 
        "награда", 
        "фестиваль",
        "концерт", 
        "игра", 
        "криптовалюта", 
        "NFT", 
        "ТикТок", 
        "YouTube", 
        "Instagram", 
        "распродажа", 
        "скидка", 
        "мода", 
        "казино"
    ],
    'ko': [
        "스포츠", 
        "축구", 
        "영화", 
        "음악", 
        "연예인", 
        "주식", 
        "IPO", 
        "스타트업", 
        "상", 
        "페스티벌",
        "콘서트", 
        "게임", 
        "암호화폐", 
        "NFT", 
        "틱톡", 
        "유튜브", 
        "인스타그램", 
        "세일", 
        "할인", 
        "패션", 
        "카지노"
    ],
    'ar': [
        "رياضة", 
        "كرة القدم", 
        "فيلم", 
        "موسيقى", 
        "مشاهير", 
        "سهم", 
        "IPO", 
        "شركة ناشئة", 
        "جائزة", 
        "مهرجان",
        "حفلة موسيقية", 
        "لعبة", 
        "عملات رقمية", 
        "NFT", 
        "تيك توك", 
        "يوتيوب", 
        "انستغرام", 
        "تخفيضات", 
        "خصم", 
        "موضة", 
        "كازينو"
    ],
    'hi': [
        "खेल", 
        "फुटबॉल", 
        "फिल्म", 
        "संगीत", 
        "सेलिब्रिटी", 
        "शेयर", 
        "IPO", 
        "स्टार्टअप", 
        "पुरस्कार", 
        "त्योहार",
        "संगीत समारोह", 
        "खेल", 
        "क्रिप्टो", 
        "NFT", 
        "टिकटोक", 
        "यूट्यूब", 
        "इंस्टाग्राम", 
        "सेल", 
        "डिस्काउंट", 
        "फैशन", 
        "कैसीनो"
    ],
    'vi': [
        "thể thao", 
        "bóng đá", 
        "phim", 
        "âm nhạc", 
        "người nổi tiếng", 
        "cổ phiếu", 
        "IPO", 
        "khởi nghiệp", 
        "giải thưởng", 
        "lễ hội",
        "hòa nhạc", 
        "trò chơi", 
        "tiền điện tử", 
        "NFT", 
        "TikTok", 
        "YouTube", 
        "Instagram", 
        "giảm giá", 
        "khuyến mãi", 
        "thời trang", 
        "casino"
    ],
    'th': [
        "กีฬา", 
        "ฟุตบอล", 
        "ภาพยนตร์", 
        "ดนตรี", 
        "คนดัง", 
        "หุ้น", 
        "IPO", 
        "สตาร์ทอัพ", 
        "รางวัล", 
        "เทศกาล",
        "คอนเสิร์ต", 
        "เกม", 
        "คริปโต", 
        "NFT", 
        "TikTok", 
        "YouTube", 
        "Instagram", 
        "ลดราคา", 
        "แฟชั่น", 
        "คาสิโน"
    ],
    'id': [
        "olahraga", 
        "sepak bola", 
        "film", 
        "musik", 
        "selebriti", 
        "saham", 
        "IPO", 
        "startup", 
        "penghargaan", 
        "festival",
        "konser", 
        "permainan", 
        "kripto", 
        "NFT", 
        "TikTok", 
        "YouTube", 
        "Instagram", 
        "penjualan", 
        "diskon", 
        "mode", 
        "kasino"
    ],
    'bn': [
        "খেলা", 
        "ফুটবল", 
        "সিনেমা", 
        "সংগীত", 
        "সেলিব্রিটি", 
        "শেয়ার", 
        "আইপিও", 
        "স্টার্টআপ", 
        "পুরস্কার", 
        "উৎসব",
        "সঙ্গীতানুষ্ঠান", 
        "খেলা", 
        "ক্রিপ্টো", 
        "NFT", 
        "টিকটক", 
        "ইউটিউব", 
        "ইনস্টাগ্রাম", 
        "বিক্রয়", 
        "ছাড়", 
        "ফ্যাশন", 
        "ক্যাসিনো"
    ],
    'ms': [
        "sukan", 
        "bola sepak", 
        "filem", 
        "muzik", 
        "selebriti", 
        "saham", 
        "IPO", 
        "permulaan", 
        "anugerah", 
        "festival",
        "konsert", 
        "permainan", 
        "kripto", 
        "NFT", 
        "TikTok", 
        "YouTube", 
        "Instagram", 
        "jualan", 
        "diskaun", 
        "fesyen", 
        "kasino"
    ],
    'ur': [
        "کھیل", 
        "فٹ بال", 
        "فلم", 
        "موسیقی", 
        "مشہور شخصیت", 
        "شیئر", 
        "آئی پی او", 
        "اسٹارٹ اپ", 
        "ایوارڈ", 
        "تہوار",
        "کنسرٹ", 
        "کھیل", 
        "کرپٹو", 
        "NFT", 
        "ٹک ٹاک", 
        "یوٹیوب", 
        "انسٹاگرام", 
        "سیل", 
        "رعایت", 
        "فیشن", 
        "کاسینو"
    ],
    'ta': [
        "விளையாட்டு", 
        "கால்பந்து", 
        "திரைப்படம்", 
        "இசை", 
        "பிரபலங்கள்", 
        "பங்கு", 
        "ஐபிஓ", 
        "ஸ்டார்ட்அப்", 
        "விருது", 
        "விழா",
        "கச்சேரி", 
        "விளையாட்டு", 
        "கிரிப்டோ", 
        "NFT", 
        "டிக்டாக்", 
        "யூடியூப்", 
        "இன்ஸ்டாகிராம்", 
        "விற்பனை", 
        "தள்ளுபடி", 
        "ஃபேஷன்", 
        "காசினோ"
    ],
    'te': [
        "క్రీడలు", 
        "ఫుట్‌బాల్", 
        "సినిమా", 
        "సంగీతం", 
        "ప్రసిద్ధి", 
        "షేరు", 
        "ఐపిఒ", 
        "స్టార్టప్", 
        "అవార్డు", 
        "పండుగ",
        "కచేరి", 
        "గేమ్", 
        "క్రిప్టో", 
        "NFT", 
        "టిక్‌టాక్", 
        "యూట్యూబ్", 
        "ఇన్‌స్టాగ్రామ్", 
        "అమ్మకాలు", 
        "డిస్కౌంట్", 
        "ఫ్యాషన్", 
        "కాసినో"
    ],
    'kn': [
        "ಕ್ರೀಡೆ", 
        "ಫುಟ್ಬಾಲ್", 
        "ಚಲನಚಿತ್ರ", 
        "ಸಂಗೀತ", 
        "ಪ್ರಸಿದ್ಧಿ", 
        "ಹಂಚಿಕೆ", 
        "ಐಪಿಒ", 
        "ಸ್ಟಾರ್ಟಪ್", 
        "ಪ್ರಶಸ್ತಿ", 
        "ಹಬ್ಬ",
        "ಕಚೇರಿ", 
        "ಆಟ", 
        "ಕ್ರಿಪ್ಟೋ", 
        "NFT", 
        "ಟಿಕ್ಟಾಕ್", 
        "ಯೂಟ್ಯೂಬ್", 
        "ಇನ್ಸ್ಟಾಗ್ರಾಂ", 
        "ಮಾರಾಟ", 
        "ರಿಯಾಯಿತಿ", 
        "ಫ್ಯಾಷನ್", 
        "ಕ್ಯಾಸಿನೋ"
    ],
    'fil': [
        "palakasan", 
        "football", 
        "pelikula", 
        "musika", 
        "sikat", 
        "stock", 
        "IPO", 
        "startup", 
        "gawad", 
        "pista",
        "konsiyerto", 
        "laro", 
        "crypto", 
        "NFT", 
        "TikTok", 
        "YouTube", 
        "Instagram", 
        "sale", 
        "discount", 
        "fashion", 
        "casino"
    ],
}