# constants/gnews_search_keywords.py
# This file contains search keywords for Google News Crawler categorized by language.

SEARCH_KEYWORDS = {
    'en': [
        "Food transport", 
        "Food logistics", 
        "Food distribution", 
        "Cold chain logistics", 
        "Refrigerated transport", 
        "Temperature-controlled logistics", 
        "Frozen food transport", 
        "Perishable goods transportation", 
        "Fresh produce logistics", 
        "Cold storage", 
        "Transport safety", 
        "Cold chain", 
        "Cold storage facilities", 
        "Refrigeration technology", 
        "Temperature monitoring", 
        "Thermal packaging", 
        "Vaccine logistics", 
        "Food spoilage prevention", 
        "Shelf life optimization", 
        "Quality control logistics", 
        "Temperature-sensitive goods", 
        "Food sourcing", 
        "Farm-to-table logistics", 
        "Food traceability", 
        "Food safety", 
        "Supply chain transparency", 
        "Agricultural supply chain", 
        "Food procurement", 
        "Supply chain resilience", 
        "Food contamination prevention", 
        "Traceability systems", 
        "Supply chain visibility", 
        "Food recalls", 
        "Food labeling compliance", 
        "Food packaging solutions", 
        "Packaging innovation", 
        "Food packaging safety", 
        "Sustainable packaging", 
        "Biodegradable packaging", 
        "Food waste management", 
        "Packaging integrity", 
        "Packaging logistics", 
        "Food-grade packaging materials", 
        "Packaging compliance standards", 
        "Sustainable supply chains", 
        "Carbon footprint reduction", 
        "Emissions reduction", 
        "Eco-friendly logistics", 
        "Food loss reduction", 
        "Waste minimization", 
        "Environmental compliance", 
        "Renewable energy logistics", 
        "Green logistics", 
        "Circular economy in food logistics", 
        "Food transportation regulations", 
        "HACCP compliance", 
        "Food security logistics", 
        "Seafood logistics", 
        "Meat transport", 
        "Dairy logistics", 
        "Fresh produce distribution", 
        "Grain logistics", 
        "Beverage supply chain", 
        "Organic food logistics", 
        "Frozen foods", 
        "Bulk food transportation", 
        "Global food distribution", 
        "Cross-border logistics", 
        "International cold chain", 
        "Import-export logistics"
    ],
    'ja': [
        "食品輸送",
        "コールドチェーン物流",
        "冷蔵輸送",
        "生鮮品輸送",
        "食品安全",
        "サプライチェーンの透明性",
        "食品リコール",
        "包装イノベーション",
        "持続可能なサプライチェーン",
        "食品ロス管理",
        "水産物流通",
        "肉類輸送",
        "乳製品物流",
        "青果流通"
    ],
    'zh-CN': [
        "食品运输",
        "冷链物流",
        "冷藏运输",
        "易腐货物运输",
        "食品安全",
        "供应链透明度",
        "食品召回",
        "包装创新",
        "可持续供应链",
        "食品废弃物管理",
        "海产品物流",
        "肉类运输",
        "乳制品物流",
        "新鲜农产品配送"
    ],
    'zh-TW': [
        "食品運輸",
        "冷鏈物流",
        "冷藏運輸",
        "易腐貨物運輸",
        "食品安全",
        "供應鏈透明度",
        "食品召回",
        "包裝創新",
        "永續供應鏈",
        "食品廢棄物管理",
        "海鮮物流",
        "肉類運輸",
        "乳製品物流",
        "新鮮農產品配送"
    ],
    'es': [
        "transporte de alimentos",
        "logística de cadena de frío",
        "transporte refrigerado",
        "transporte de productos perecederos",
        "seguridad alimentaria",
        "transparencia de la cadena de suministro",
        "retiro de alimentos",
        "innovación en envases",
        "cadenas de suministro sostenibles",
        "gestión de residuos alimentarios",
        "logística de mariscos",
        "transporte de carne",
        "logística de productos lácteos",
        "distribución de productos frescos"
    ],
    'de': [
        "Lebensmitteltransport",
        "Kühlkettenlogistik",
        "gekühlter Transport",
        "Transport verderblicher Waren",
        "Lebensmittelsicherheit",
        "Transparenz der Lieferkette",
        "Lebensmittelrückruf",
        "Verpackungsinnovation",
        "nachhaltige Lieferketten",
        "Lebensmittelabfallmanagement",
        "Fischereilogistik",
        "Fleischtransport",
        "Milchlogistik",
        "Frischwarendistribution"
    ],
    'ru': [
        "перевозка продуктов",
        "логистика холодовой цепи",
        "рефрижераторные перевозки",
        "перевозка скоропортящихся товаров",
        "безопасность пищевых продуктов",
        "прозрачность цепочки поставок",
        "отзыв продуктов питания",
        "инновации в упаковке",
        "устойчивые цепочки поставок",
        "управление пищевыми отходами",
        "логистика морепродуктов",
        "перевозка мяса",
        "логистика молочных продуктов",
        "распределение свежих продуктов"
    ],
    'ko': [
        "식품 운송",
        "콜드체인 물류",
        "냉장 운송",
        "부패하기 쉬운 상품 운송",
        "식품 안전",
        "공급망 투명성",
        "식품 리콜",
        "포장 혁신",
        "지속 가능한 공급망",
        "식품 폐기물 관리",
        "해산물 물류",
        "육류 운송",
        "유제품 물류",
        "신선 농산물 유통"
    ],
    'ar': [
        "نقل الغذاء",
        "لوجستيات سلسلة التبريد",
        "نقل مبرد",
        "نقل السلع القابلة للتلف",
        "سلامة الغذاء",
        "شفافية سلسلة التوريد",
        "سحب الغذاء",
        "ابتكار التغليف",
        "سلاسل التوريد المستدامة",
        "إدارة نفايات الغذاء",
        "لوجستيات المأكولات البحرية",
        "نقل اللحوم",
        "لوجستيات الألبان",
        "توزيع المنتجات الطازجة"
    ],
    'hi': [
        "खाद्य परिवहन",
        "कोल्ड चेन लॉजिस्टिक्स",
        "रेफ्रिजेरेटेड परिवहन",
        "नाशवान वस्तुओं का परिवहन",
        "खाद्य सुरक्षा",
        "सप्लाई चेन पारदर्शिता",
        "खाद्य रिकॉल",
        "पैकेजिंग नवाचार",
        "सतत आपूर्ति श्रृंखलाएं",
        "खाद्य अपशिष्ट प्रबंधन",
        "समुद्री भोजन लॉजिस्टिक्स",
        "मांस परिवहन",
        "डेयरी लॉजिस्टिक्स",
        "ताजा उत्पाद वितरण"
    ],
    'vi': [
        "vận chuyển thực phẩm",
        "chuỗi cung ứng lạnh",
        "vận chuyển đông lạnh",
        "vận chuyển hàng dễ hỏng",
        "an toàn thực phẩm",
        "minh bạch chuỗi cung ứng",
        "thu hồi thực phẩm",
        "đổi mới bao bì",
        "chuỗi cung ứng bền vững",
        "quản lý rác thải thực phẩm",
        "logistics thủy sản",
        "vận chuyển thịt",
        "logistics sữa",
        "phân phối sản phẩm tươi"
    ],
    'th': [
        "ขนส่งอาหาร",
        "โลจิสติกส์โซ่เย็น",
        "ขนส่งแบบแช่เย็น",
        "ขนส่งสินค้าที่เน่าเสียง่าย",
        "ความปลอดภัยของอาหาร",
        "ความโปร่งใสของซัพพลายเชน",
        "เรียกคืนอาหาร",
        "นวัตกรรมบรรจุภัณฑ์",
        "ซัพพลายเชนที่ยั่งยืน",
        "การจัดการขยะอาหาร",
        "โลจิสติกส์อาหารทะเล",
        "ขนส่งเนื้อสัตว์",
        "โลจิสติกส์ผลิตภัณฑ์นม",
        "จัดจำหน่ายผักสด"
    ],
    'id': [
        "pengangkutan makanan",
        "logistik rantai dingin",
        "pengangkutan berpendingin",
        "pengangkutan barang mudah rusak",
        "keamanan makanan",
        "transparansi rantai pasokan",
        "penarikan makanan",
        "inovasi kemasan",
        "rantai pasokan berkelanjutan",
        "manajemen limbah makanan",
        "logistik makanan laut",
        "pengangkutan daging",
        "logistik susu",
        "distribusi hasil panen segar"
    ],
    'bn': [
        "খাদ্য পরিবহন",
        "কোল্ড চেইন লজিস্টিক্স",
        "রেফ্রিজারেটেড পরিবহন",
        "নাশযোগ্য পণ্য পরিবহন",
        "খাদ্য নিরাপত্তা",
        "সরবরাহ চেইনের স্বচ্ছতা",
        "খাদ্য প্রত্যাহার",
        "প্যাকেজিং উদ্ভাবন",
        "টেকসই সরবরাহ চেইন",
        "খাদ্য বর্জ্য ব্যবস্থাপনা",
        "সামুদ্রিক খাদ্য লজিস্টিক্স",
        "মাংস পরিবহন",
        "দুগ্ধজাত পণ্য লজিস্টিক্স",
        "তাজা পণ্য বিতরণ"
    ],
    'ms': [
        "pengangkutan makanan",
        "logistik rantaian sejuk",
        "pengangkutan berpendingin",
        "pengangkutan barang mudah rosak",
        "keselamatan makanan",
        "ketelusan rantaian bekalan",
        "penarikan balik makanan",
        "inovasi pembungkusan",
        "rantaian bekalan lestari",
        "pengurusan sisa makanan",
        "logistik makanan laut",
        "pengangkutan daging",
        "logistik tenusu",
        "pengedaran hasil segar"
    ],
    'ur': [
        "خوراک کی ترسیل",
        "کولڈ چین لاجسٹکس",
        "ریفریجریٹڈ ٹرانسپورٹ",
        "خراب ہونے والی اشیاء کی ترسیل",
        "خوراک کی حفاظت",
        "سپلائی چین شفافیت",
        "خوراک کی واپسی",
        "پیکیجنگ میں جدت",
        "پائیدار سپلائی چینز",
        "خوراک کے فضلے کا انتظام",
        "سمندری خوراک لاجسٹکس",
        "گوشت کی ترسیل",
        "ڈیری لاجسٹکس",
        "تازہ مصنوعات کی تقسیم"
    ],
    'ta': [
        "உணவு போக்குவரத்து",
        "குளிர்சென் логிஸ்டிக்ஸ்",
        "குளிர்வதற்கான போக்குவரத்து",
        "மெத்த பொருட்கள் போக்குவரத்து",
        "உணவு பாதுகாப்பு",
        "விநியோக சங்கிலி வெளிப்படைத்தன்மை",
        "உணவு மீள்மாற்றங்கள்",
        "பேக்கேஜிங் புதுமை",
        "நிலையான விநியோக சங்கிலிகள்",
        "உணவு கழிவுகள் மேலாண்மை",
        "மீன் போக்குவரத்து",
        "மாமிசம் போக்குவரத்து",
        "பால்வகை போக்குவரத்து",
        "பசுமை காய்கறி விநியோகம்"
    ],
    'te': [
        "ఆహార రవాణా",
        "కాల్డ్ చైన్ లాజిస్టిక్స్",
        "ఉపశమనం రవాణా",
        "పర్యావరణ సరుకు రవాణా",
        "ఆహార భద్రత",
        "సప్లై చైన్ పారదర్శకత",
        "ఆహార రికాల్‌లు",
        "ప్యాకేజింగ్ నూతనత",
        "సుసంవిధాన సరఫరా గొలుసులు",
        "ఆహార వ్యర్థాల నిర్వహణ",
        "సముద్రపు ఆహార రవాణా",
        "మాంసం రవాణా",
        "పాలు ఉత్పత్తుల లాజిస్టిక్స్",
        "తాజా కూరగాయల పంపిణీ"
    ],
    'kn': [
        "ಆಹಾರ ಸಾರಿಗೆ",
        "ಶೀತ ಸರಪಳಿ ಲಾಜಿಸ್ಟಿಕ್ಸ್",
        "ಶೀತೀಕರಣ ಸಾರಿಗೆ",
        "ನಾಶವಾಗುವ ಸರಕುಗಳ ಸಾರಿಗೆ",
        "ಆಹಾರ ಸುರಕ್ಷತೆ",
        "ಪೂರೈಕೆ ಸರಪಳಿ ಪಾರದರ್ಶಕತೆ",
        "ಆಹಾರ ಹಿಂದಿರುಗಿಕೆ",
        "ಪ್ಯಾಕೇಜಿಂಗ್ ನವೀನತೆ",
        "ಸ್ಥಿರ ಪೂರೈಕೆ ಸರಪಳಿಗಳು",
        "ಆಹಾರ ತ್ಯಾಜ್ಯ ನಿರ್ವಹಣೆ",
        "ಸಮುದ್ರ ಆಹಾರ ಸಾರಿಗೆ",
        "ಮಾಂಸಾಹಾರಿ ಆಹಾರ ಸಾರಿಗೆ",
        "ಹಾಲಿನ ಉತ್ಪನ್ನಗಳ ಲಾಜಿಸ್ಟಿಕ್ಸ್",
        "ತಾಜಾ ತರಕಾರಿ ಹಂಚಿಕೆ"
    ],
    'fil': [
        "pagdadala ng pagkain",
        "cold chain logistics",
        "pinalamig na transportasyon",
        "transportasyon ng nabubulok na kalakal",
        "kaligtasan ng pagkain",
        "transparency ng supply chain",
        "food recalls",
        "inobasyon sa packaging",
        "napapanatiling supply chain",
        "pamamahala ng basura sa pagkain",
        "logistics ng pagkaing dagat",
        "transportasyon ng karne",
        "logistics ng dairy",
        "pamamahagi ng sariwang gulay"
    ],
}

# SEARCH_KEYWORDS = {
#     "en": ["food security", "climate change"],
#     "ja": ["食料安全保障", "気候変動"],
#     "es": ["seguridad alimentaria", "cambio climático"],
# }